service: ${file(./package.json):name}
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: ${env:STAGE}
  region: us-east-1

package:
  individually: true

custom:
  rust:
    dockerless: true

plugins:
  - serverless-rust

functions:
  func:
    handler: "sls-lambda-rust"