frameworkVersion: "3"

service: ${self:custom.name}

custom:
  name: ${file(./package.json):name}
  config: ${file(../infra/config/${opt:stage}.js)}
  customDomain: ${file(../infra/customDomain.js)}
  rust:
    dockerless: true

provider:
  name: aws
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      func:
        path: ./

functions:
  func:
    image:
      name: func
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-domain-manager